// Copies the self-hosted fonts and generates public/icons.js from the official Phosphor icon set.
// Run after changing ICONS below:  npm run build:assets   (needs the devDependencies installed)
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const geist = path.join(root, 'node_modules', 'geist', 'dist', 'fonts');
const phosphor = path.join(root, 'node_modules', '@phosphor-icons', 'core', 'assets', 'regular');

// name used in app.js -> Phosphor icon file (regular weight, one family everywhere)
const ICONS = {
  bell: 'bell', flame: 'fire', send: 'paper-plane-tilt', msg: 'chat-circle-text', list: 'list-bullets',
  note: 'file-text', edit: 'note-pencil', plus: 'plus', copy: 'copy', refresh: 'arrow-clockwise', video: 'video-camera',
  plug: 'cloud-check', check: 'check', open: 'arrow-up-right', chev: 'caret-right', down: 'caret-down',
  alert: 'warning', x: 'x', info: 'info', users: 'users-three', search: 'magnifying-glass', undo: 'arrow-counter-clockwise',
  facebook: 'facebook-logo', instagram: 'instagram-logo', ok: 'check-circle', clock: 'clock',
  asc: 'sort-ascending', desc: 'sort-descending',
};

const fonts = [
  [path.join(geist, 'geist-sans', 'Geist-Variable.woff2'), 'Geist-Variable.woff2'],
  [path.join(geist, 'geist-mono', 'GeistMono-Variable.woff2'), 'GeistMono-Variable.woff2'],
];
fs.mkdirSync(path.join(root, 'public', 'fonts'), { recursive: true });
fonts.forEach(([from, to]) => fs.copyFileSync(from, path.join(root, 'public', 'fonts', to)));
fs.copyFileSync(path.join(root, 'node_modules', 'geist', 'LICENSE.txt'), path.join(root, 'public', 'fonts', 'LICENSE-Geist-OFL.txt'));

const out = {};
Object.entries(ICONS).forEach(([name, file]) => {
  const svg = fs.readFileSync(path.join(phosphor, `${file}.svg`), 'utf8');
  const inner = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(svg);
  if (!inner) throw new Error(`Unexpected SVG for ${file}`);
  out[name] = inner[1].trim();
});
fs.writeFileSync(path.join(root, 'public', 'icons.js'),
  `// Generated by scripts/build-assets.js from @phosphor-icons/core (MIT). Do not edit by hand.\nwindow.ICONS = ${JSON.stringify(out, null, 1)};\n`);
console.log(`fonts copied, ${Object.keys(out).length} icons written`);
